---
deployment:
  tasks:
    - export DEPLOYPATH=/home/public_html/Beach-Houses-In-Mayaro-Website/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp blog.html $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH
    - /bin/cp sitemap.xml $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R forms $DEPLOYPATH